name: diagrams.net site
permalink: /blog/:slug

baseurl: '/test-web'


collections:
  - faq

faq-categories: [Confluence Cloud, Confluence Server, Customisation, Shapes, Connectors, Plugins, Integrations, Export]
